// ---------------Index Section--------------------------------
exports.indexPage = function(d) {
  var pagHTML = `
    <!DOCTYPE html>
    <html>
    <head>
        <title>Index</title>
        <meta charset="utf-8"/>
        <link rel="icon" href="favicon.png"/>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-green">
                <h1>Index</h1>
            </header>

            <div class="w3-container">
                <ul class="w3-ul w3-card-4" style="width:50%">
                    <li><a href="/movies">Movies</a></li>
                    <li><a href="/actors">Actors</a></li>
                    <li><a href="/genres">Genres</a></li>
                </ul>
            </div>
            <footer class="w3-container w3-green">
                <address>Gerado por galuno::RPCW2022 em ${d} - [<a href="/movies">Voltar</a>]</address>
            </footer>
        </div>
    </body>
    </html>
    `
  return pagHTML
}


// ---------------Movies Section--------------------------------
exports.moviesListPage = function(mlist, d) {
  var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Movies</title>
        </head>
        <body>
            <div class="w3-card-4">

                <header class="w3-container w3-green">
                    <h1>Movies List
                    </h1>
                    
                </header>
        
                <div class="w3-container">
                    <table class="w3-table-all">
                        <tr>
                            <th>Id</th><th>Name</th><th>Year</th>
                            <th>Actions</th>
                        </tr>
                `
  for (let i = 0; i < mlist.length; i++) {
    pagHTML += `
                <tr>
                    <td>${mlist[i].id}</td>
                    <td>
                        <a href="/movies/${mlist[i].id}">
                            ${mlist[i].title}
                        </a>
                    </td>
                    <td>${mlist[i].year}</td>
                    <td>
                        [<a href="/movies/edit/${mlist[i].id}">Edit</a>][<a href="/movies/delete/${mlist[i].id}">Delete</a>]
                    </td>
                </tr>
        `
  }

  pagHTML += `
            </table>
            </div>
                <footer class="w3-container w3-green">
                    <h5>Generated by RPCW2023 in ${d}</h5>
                </footer>
            </div>
        </body>
    </html>
    `
  return pagHTML
}

exports.moviePage = function(movie, d) {
  var pagHTML = `
    <html>
    <head>
        <title>Movie: ${movie.Id}</title>
        <meta charset="utf-8"/>
        <link rel="icon" href="favicon.png"/>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-green">
                <h1>${movie.title}</h1>
            </header>

            <div class="w3-container">
                <ul class="w3-ul w3-card-4" style="width:50%">
                    <li><b>ID: </b> ${movie.id}</li>
                    <li><b>Year of release: </b> ${movie.year}</li>
            `
  if (movie.genres.length > 0) {
    pagHTML += `<li><b>Genres: </b> ${movie.genres}`
  }
  if (movie.cast.length > 0) {
    pagHTML += `<li><b>Cast: </b> ${movie.cast}`
  }

  pagHTML += `</ul></div>
            <footer class="w3-container w3-green">
                <address>Gerado por galuno::RPCW2022 em ${d} - [<a href="/movies">Voltar</a>]</address>
            </footer>
        </div>
    </body>
    </html>
    `
  return pagHTML
}

// ---------------Actors Section--------------------------------
exports.actorsListPage = function(alist, d) {
  var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Actors</title>
        </head>
        <body>
            <div class="w3-card-4">

                <header class="w3-container w3-blue">
                    <h1>Actors List</h1>
                    
                </header>
        
                <div class="w3-container">
                    <table class="w3-table-all">
                        <tr>
                            <th>Id</th><th>Name</th>
                        </tr>
                `
  for (let i = 0; i < alist.length; i++) {
    pagHTML += `
                <tr>
                    <td>${alist[i].id}</td>
                    <td>
                        <a href="/actors/${alist[i].id}">
                            ${alist[i].name}
                        </a>
                    </td>
                </tr>
        `
  }

  pagHTML += `
            </table>
            </div>
                <footer class="w3-container w3-blue">
                    <h5>Generated by RPCW2023 in ${d}</h5>
                </footer>
            </div>
        </body>
    </html>
    `
  return pagHTML
}

exports.actorPage = function(actor, d) {
  var pagHTML = `
    <html>
    <head>
        <title>Movie: ${actor.id}</title>
        <meta charset="utf-8"/>
        <link rel="icon" href="favicon.png"/>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-blue">
                <h1>${actor.name}</h1>
            </header>
            <footer class="w3-container w3-blue">
                <address>Gerado por galuno::RPCW2022 em ${d} - [<a href="/actors">Voltar</a>]</address>
            </footer>
        </div>
    </body>
    </html>
    `
  return pagHTML
}

// ---------------Genres Section--------------------------------
exports.genresListPage = function(glist, d) {
  var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Actors</title>
        </head>
        <body>
            <div class="w3-card-4">

                <header class="w3-container w3-red">
                    <h1>Genres List</h1>
                    
                </header>
        
                <div class="w3-container">
                    <table class="w3-table-all">
                        <tr>
                            <th>Id</th><th>Name</th>
                        </tr>
                `
  for (let i = 0; i < glist.length; i++) {
    pagHTML += `
                <tr>
                    <td>${glist[i].id}</td>
                    <td>
                        <a href="/genres/${glist[i].id}">
                            ${glist[i].name}
                        </a>
                    </td>
                </tr>
        `
  }

  pagHTML += `
            </table>
            </div>
                <footer class="w3-container w3-red">
                    <h5>Generated by RPCW2023 in ${d}</h5>
                </footer>
            </div>
        </body>
    </html>
    `
  return pagHTML
}

exports.genrePage = function(genre, d) {
  var pagHTML = `
    <html>
    <head>
        <title>Movie: ${genre.id}</title>
        <meta charset="utf-8"/>
        <link rel="icon" href="favicon.png"/>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-red">
                <h1>${genre.name}</h1>
            </header>
            <footer class="w3-container w3-red">
                <address>Gerado por galuno::RPCW2022 em ${d} - [<a href="/genres">Voltar</a>]</address>
            </footer>
        </div>
    </body>
    </html>
    `
  return pagHTML
}

// -------------- Error Treatment ------------------------------
exports.errorPage = function(errorMessage, d) {
  return `
    <p>${d}: Error: ${errorMessage}</p>
    `
}
